export const GET_DOCUMENTACIONES = "GET_DOCUMENTACIONES";
export const GET_DOC_EMPLEADO = "GET_DOC_EMPLEADO"
export const SAVE_IDS = "SAVE_IDS"
export const CLEAN_IDS_DOC = "CLEAN_IDS_DOC"
export const DELETE_DOC_EMPLEADO = "DELETE_DOC_EMPLEADO"