export const GET_DOMICILIOS = "GET_DOMICILIOS"
export const ADD_DOMICILIO = "ADD_DOMICILIO";
export const DOMICILIO_SELECTED = "DOMICILIO_SELECTED";
export const DELETE_DOMICILIO = "DELETE_DOMICILIO"

export const SAVE_ID_DOM = "SAVE_ID_DOM"